### ISSUE TITLE
Readme.md y versión de Unity

### ISSUE THREAD

**Issue by crannnabethadh** [MiguelRubioS2P/Metamorfosis#1]
Hola, **genial proyecto**, me encata.
Estoy probando los issues en Github.

Hecho de menos un **Readme.md** donde ponga algo sobre el proyecto.

Además lo he clonado pero no se si abrirlo con Unity 2018.4 LTS, 2019.2.X o 2019.3.X. Podríasis indicar en el Readme.md con que versión estais desarrollandolo?

Gracias

**Comment by MiguelRubioS2P** [comment]
Ya esta añadido.

Probando el flujo de los issues.

Voy a hacer el comentario y cerrar issue.
